// source: api_specification_am_fleet_coordination.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

// var jspb = require('google-protobuf');
import * as jspb from 'google-protobuf'
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.fleetcoordination.ChangeFleetManagerRequest', null, global);
goog.exportSymbol('proto.fleetcoordination.ChangeFleetManagerResponse', null, global);
goog.exportSymbol('proto.fleetcoordination.CreateNewFleetRequest', null, global);
goog.exportSymbol('proto.fleetcoordination.CreateNewFleetResponse', null, global);
goog.exportSymbol('proto.fleetcoordination.DeleteFleetRequest', null, global);
goog.exportSymbol('proto.fleetcoordination.DeleteFleetResponse', null, global);
goog.exportSymbol('proto.fleetcoordination.ErrorDetail', null, global);
goog.exportSymbol('proto.fleetcoordination.Fleet', null, global);
goog.exportSymbol('proto.fleetcoordination.ListFleetManagersRequest', null, global);
goog.exportSymbol('proto.fleetcoordination.ListFleetManagersResponse', null, global);
goog.exportSymbol('proto.fleetcoordination.ListFleetsRequest', null, global);
goog.exportSymbol('proto.fleetcoordination.ListFleetsResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fleetcoordination.CreateNewFleetRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fleetcoordination.CreateNewFleetRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.fleetcoordination.CreateNewFleetRequest.displayName = 'proto.fleetcoordination.CreateNewFleetRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fleetcoordination.CreateNewFleetResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fleetcoordination.CreateNewFleetResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.fleetcoordination.CreateNewFleetResponse.displayName = 'proto.fleetcoordination.CreateNewFleetResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fleetcoordination.ChangeFleetManagerRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fleetcoordination.ChangeFleetManagerRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.fleetcoordination.ChangeFleetManagerRequest.displayName = 'proto.fleetcoordination.ChangeFleetManagerRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fleetcoordination.ChangeFleetManagerResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fleetcoordination.ChangeFleetManagerResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.fleetcoordination.ChangeFleetManagerResponse.displayName = 'proto.fleetcoordination.ChangeFleetManagerResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fleetcoordination.ListFleetsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fleetcoordination.ListFleetsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.fleetcoordination.ListFleetsRequest.displayName = 'proto.fleetcoordination.ListFleetsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fleetcoordination.ListFleetsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.fleetcoordination.ListFleetsResponse.repeatedFields_, null);
};
goog.inherits(proto.fleetcoordination.ListFleetsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.fleetcoordination.ListFleetsResponse.displayName = 'proto.fleetcoordination.ListFleetsResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fleetcoordination.ListFleetManagersRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fleetcoordination.ListFleetManagersRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.fleetcoordination.ListFleetManagersRequest.displayName = 'proto.fleetcoordination.ListFleetManagersRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fleetcoordination.ListFleetManagersResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.fleetcoordination.ListFleetManagersResponse.repeatedFields_, null);
};
goog.inherits(proto.fleetcoordination.ListFleetManagersResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.fleetcoordination.ListFleetManagersResponse.displayName = 'proto.fleetcoordination.ListFleetManagersResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fleetcoordination.DeleteFleetRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fleetcoordination.DeleteFleetRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.fleetcoordination.DeleteFleetRequest.displayName = 'proto.fleetcoordination.DeleteFleetRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fleetcoordination.DeleteFleetResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fleetcoordination.DeleteFleetResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.fleetcoordination.DeleteFleetResponse.displayName = 'proto.fleetcoordination.DeleteFleetResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fleetcoordination.Fleet = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fleetcoordination.Fleet, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.fleetcoordination.Fleet.displayName = 'proto.fleetcoordination.Fleet';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fleetcoordination.ErrorDetail = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fleetcoordination.ErrorDetail, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.fleetcoordination.ErrorDetail.displayName = 'proto.fleetcoordination.ErrorDetail';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fleetcoordination.CreateNewFleetRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.fleetcoordination.CreateNewFleetRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fleetcoordination.CreateNewFleetRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fleetcoordination.CreateNewFleetRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    location: jspb.Message.getFieldWithDefault(msg, 1, ""),
    fleetmanager: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fleetcoordination.CreateNewFleetRequest}
 */
proto.fleetcoordination.CreateNewFleetRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fleetcoordination.CreateNewFleetRequest;
  return proto.fleetcoordination.CreateNewFleetRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fleetcoordination.CreateNewFleetRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fleetcoordination.CreateNewFleetRequest}
 */
proto.fleetcoordination.CreateNewFleetRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setLocation(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setFleetmanager(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fleetcoordination.CreateNewFleetRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fleetcoordination.CreateNewFleetRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fleetcoordination.CreateNewFleetRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fleetcoordination.CreateNewFleetRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLocation();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getFleetmanager();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string location = 1;
 * @return {string}
 */
proto.fleetcoordination.CreateNewFleetRequest.prototype.getLocation = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.fleetcoordination.CreateNewFleetRequest} returns this
 */
proto.fleetcoordination.CreateNewFleetRequest.prototype.setLocation = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string fleetManager = 2;
 * @return {string}
 */
proto.fleetcoordination.CreateNewFleetRequest.prototype.getFleetmanager = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.fleetcoordination.CreateNewFleetRequest} returns this
 */
proto.fleetcoordination.CreateNewFleetRequest.prototype.setFleetmanager = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fleetcoordination.CreateNewFleetResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.fleetcoordination.CreateNewFleetResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fleetcoordination.CreateNewFleetResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fleetcoordination.CreateNewFleetResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    fleet: (f = msg.getFleet()) && proto.fleetcoordination.Fleet.toObject(includeInstance, f),
    error: (f = msg.getError()) && proto.fleetcoordination.ErrorDetail.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fleetcoordination.CreateNewFleetResponse}
 */
proto.fleetcoordination.CreateNewFleetResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fleetcoordination.CreateNewFleetResponse;
  return proto.fleetcoordination.CreateNewFleetResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fleetcoordination.CreateNewFleetResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fleetcoordination.CreateNewFleetResponse}
 */
proto.fleetcoordination.CreateNewFleetResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.fleetcoordination.Fleet;
      reader.readMessage(value,proto.fleetcoordination.Fleet.deserializeBinaryFromReader);
      msg.setFleet(value);
      break;
    case 2:
      var value = new proto.fleetcoordination.ErrorDetail;
      reader.readMessage(value,proto.fleetcoordination.ErrorDetail.deserializeBinaryFromReader);
      msg.setError(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fleetcoordination.CreateNewFleetResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fleetcoordination.CreateNewFleetResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fleetcoordination.CreateNewFleetResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fleetcoordination.CreateNewFleetResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFleet();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.fleetcoordination.Fleet.serializeBinaryToWriter
    );
  }
  f = message.getError();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.fleetcoordination.ErrorDetail.serializeBinaryToWriter
    );
  }
};


/**
 * optional Fleet fleet = 1;
 * @return {?proto.fleetcoordination.Fleet}
 */
proto.fleetcoordination.CreateNewFleetResponse.prototype.getFleet = function() {
  return /** @type{?proto.fleetcoordination.Fleet} */ (
    jspb.Message.getWrapperField(this, proto.fleetcoordination.Fleet, 1));
};


/**
 * @param {?proto.fleetcoordination.Fleet|undefined} value
 * @return {!proto.fleetcoordination.CreateNewFleetResponse} returns this
*/
proto.fleetcoordination.CreateNewFleetResponse.prototype.setFleet = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.fleetcoordination.CreateNewFleetResponse} returns this
 */
proto.fleetcoordination.CreateNewFleetResponse.prototype.clearFleet = function() {
  return this.setFleet(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.fleetcoordination.CreateNewFleetResponse.prototype.hasFleet = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ErrorDetail error = 2;
 * @return {?proto.fleetcoordination.ErrorDetail}
 */
proto.fleetcoordination.CreateNewFleetResponse.prototype.getError = function() {
  return /** @type{?proto.fleetcoordination.ErrorDetail} */ (
    jspb.Message.getWrapperField(this, proto.fleetcoordination.ErrorDetail, 2));
};


/**
 * @param {?proto.fleetcoordination.ErrorDetail|undefined} value
 * @return {!proto.fleetcoordination.CreateNewFleetResponse} returns this
*/
proto.fleetcoordination.CreateNewFleetResponse.prototype.setError = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.fleetcoordination.CreateNewFleetResponse} returns this
 */
proto.fleetcoordination.CreateNewFleetResponse.prototype.clearError = function() {
  return this.setError(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.fleetcoordination.CreateNewFleetResponse.prototype.hasError = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fleetcoordination.ChangeFleetManagerRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.fleetcoordination.ChangeFleetManagerRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fleetcoordination.ChangeFleetManagerRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fleetcoordination.ChangeFleetManagerRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    fleet: (f = msg.getFleet()) && proto.fleetcoordination.Fleet.toObject(includeInstance, f),
    fleetmanager: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fleetcoordination.ChangeFleetManagerRequest}
 */
proto.fleetcoordination.ChangeFleetManagerRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fleetcoordination.ChangeFleetManagerRequest;
  return proto.fleetcoordination.ChangeFleetManagerRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fleetcoordination.ChangeFleetManagerRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fleetcoordination.ChangeFleetManagerRequest}
 */
proto.fleetcoordination.ChangeFleetManagerRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.fleetcoordination.Fleet;
      reader.readMessage(value,proto.fleetcoordination.Fleet.deserializeBinaryFromReader);
      msg.setFleet(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setFleetmanager(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fleetcoordination.ChangeFleetManagerRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fleetcoordination.ChangeFleetManagerRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fleetcoordination.ChangeFleetManagerRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fleetcoordination.ChangeFleetManagerRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFleet();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.fleetcoordination.Fleet.serializeBinaryToWriter
    );
  }
  f = message.getFleetmanager();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional Fleet fleet = 1;
 * @return {?proto.fleetcoordination.Fleet}
 */
proto.fleetcoordination.ChangeFleetManagerRequest.prototype.getFleet = function() {
  return /** @type{?proto.fleetcoordination.Fleet} */ (
    jspb.Message.getWrapperField(this, proto.fleetcoordination.Fleet, 1));
};


/**
 * @param {?proto.fleetcoordination.Fleet|undefined} value
 * @return {!proto.fleetcoordination.ChangeFleetManagerRequest} returns this
*/
proto.fleetcoordination.ChangeFleetManagerRequest.prototype.setFleet = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.fleetcoordination.ChangeFleetManagerRequest} returns this
 */
proto.fleetcoordination.ChangeFleetManagerRequest.prototype.clearFleet = function() {
  return this.setFleet(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.fleetcoordination.ChangeFleetManagerRequest.prototype.hasFleet = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string fleetManager = 2;
 * @return {string}
 */
proto.fleetcoordination.ChangeFleetManagerRequest.prototype.getFleetmanager = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.fleetcoordination.ChangeFleetManagerRequest} returns this
 */
proto.fleetcoordination.ChangeFleetManagerRequest.prototype.setFleetmanager = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fleetcoordination.ChangeFleetManagerResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.fleetcoordination.ChangeFleetManagerResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fleetcoordination.ChangeFleetManagerResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fleetcoordination.ChangeFleetManagerResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    result: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    error: (f = msg.getError()) && proto.fleetcoordination.ErrorDetail.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fleetcoordination.ChangeFleetManagerResponse}
 */
proto.fleetcoordination.ChangeFleetManagerResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fleetcoordination.ChangeFleetManagerResponse;
  return proto.fleetcoordination.ChangeFleetManagerResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fleetcoordination.ChangeFleetManagerResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fleetcoordination.ChangeFleetManagerResponse}
 */
proto.fleetcoordination.ChangeFleetManagerResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setResult(value);
      break;
    case 2:
      var value = new proto.fleetcoordination.ErrorDetail;
      reader.readMessage(value,proto.fleetcoordination.ErrorDetail.deserializeBinaryFromReader);
      msg.setError(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fleetcoordination.ChangeFleetManagerResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fleetcoordination.ChangeFleetManagerResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fleetcoordination.ChangeFleetManagerResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fleetcoordination.ChangeFleetManagerResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResult();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getError();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.fleetcoordination.ErrorDetail.serializeBinaryToWriter
    );
  }
};


/**
 * optional bool result = 1;
 * @return {boolean}
 */
proto.fleetcoordination.ChangeFleetManagerResponse.prototype.getResult = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.fleetcoordination.ChangeFleetManagerResponse} returns this
 */
proto.fleetcoordination.ChangeFleetManagerResponse.prototype.setResult = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional ErrorDetail error = 2;
 * @return {?proto.fleetcoordination.ErrorDetail}
 */
proto.fleetcoordination.ChangeFleetManagerResponse.prototype.getError = function() {
  return /** @type{?proto.fleetcoordination.ErrorDetail} */ (
    jspb.Message.getWrapperField(this, proto.fleetcoordination.ErrorDetail, 2));
};


/**
 * @param {?proto.fleetcoordination.ErrorDetail|undefined} value
 * @return {!proto.fleetcoordination.ChangeFleetManagerResponse} returns this
*/
proto.fleetcoordination.ChangeFleetManagerResponse.prototype.setError = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.fleetcoordination.ChangeFleetManagerResponse} returns this
 */
proto.fleetcoordination.ChangeFleetManagerResponse.prototype.clearError = function() {
  return this.setError(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.fleetcoordination.ChangeFleetManagerResponse.prototype.hasError = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fleetcoordination.ListFleetsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.fleetcoordination.ListFleetsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fleetcoordination.ListFleetsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fleetcoordination.ListFleetsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fleetcoordination.ListFleetsRequest}
 */
proto.fleetcoordination.ListFleetsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fleetcoordination.ListFleetsRequest;
  return proto.fleetcoordination.ListFleetsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fleetcoordination.ListFleetsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fleetcoordination.ListFleetsRequest}
 */
proto.fleetcoordination.ListFleetsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fleetcoordination.ListFleetsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fleetcoordination.ListFleetsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fleetcoordination.ListFleetsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fleetcoordination.ListFleetsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.fleetcoordination.ListFleetsResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fleetcoordination.ListFleetsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.fleetcoordination.ListFleetsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fleetcoordination.ListFleetsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fleetcoordination.ListFleetsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    fleetsList: jspb.Message.toObjectList(msg.getFleetsList(),
    proto.fleetcoordination.Fleet.toObject, includeInstance),
    error: (f = msg.getError()) && proto.fleetcoordination.ErrorDetail.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fleetcoordination.ListFleetsResponse}
 */
proto.fleetcoordination.ListFleetsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fleetcoordination.ListFleetsResponse;
  return proto.fleetcoordination.ListFleetsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fleetcoordination.ListFleetsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fleetcoordination.ListFleetsResponse}
 */
proto.fleetcoordination.ListFleetsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.fleetcoordination.Fleet;
      reader.readMessage(value,proto.fleetcoordination.Fleet.deserializeBinaryFromReader);
      msg.addFleets(value);
      break;
    case 2:
      var value = new proto.fleetcoordination.ErrorDetail;
      reader.readMessage(value,proto.fleetcoordination.ErrorDetail.deserializeBinaryFromReader);
      msg.setError(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fleetcoordination.ListFleetsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fleetcoordination.ListFleetsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fleetcoordination.ListFleetsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fleetcoordination.ListFleetsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFleetsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.fleetcoordination.Fleet.serializeBinaryToWriter
    );
  }
  f = message.getError();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.fleetcoordination.ErrorDetail.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Fleet fleets = 1;
 * @return {!Array<!proto.fleetcoordination.Fleet>}
 */
proto.fleetcoordination.ListFleetsResponse.prototype.getFleetsList = function() {
  return /** @type{!Array<!proto.fleetcoordination.Fleet>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.fleetcoordination.Fleet, 1));
};


/**
 * @param {!Array<!proto.fleetcoordination.Fleet>} value
 * @return {!proto.fleetcoordination.ListFleetsResponse} returns this
*/
proto.fleetcoordination.ListFleetsResponse.prototype.setFleetsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.fleetcoordination.Fleet=} opt_value
 * @param {number=} opt_index
 * @return {!proto.fleetcoordination.Fleet}
 */
proto.fleetcoordination.ListFleetsResponse.prototype.addFleets = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.fleetcoordination.Fleet, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.fleetcoordination.ListFleetsResponse} returns this
 */
proto.fleetcoordination.ListFleetsResponse.prototype.clearFleetsList = function() {
  return this.setFleetsList([]);
};


/**
 * optional ErrorDetail error = 2;
 * @return {?proto.fleetcoordination.ErrorDetail}
 */
proto.fleetcoordination.ListFleetsResponse.prototype.getError = function() {
  return /** @type{?proto.fleetcoordination.ErrorDetail} */ (
    jspb.Message.getWrapperField(this, proto.fleetcoordination.ErrorDetail, 2));
};


/**
 * @param {?proto.fleetcoordination.ErrorDetail|undefined} value
 * @return {!proto.fleetcoordination.ListFleetsResponse} returns this
*/
proto.fleetcoordination.ListFleetsResponse.prototype.setError = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.fleetcoordination.ListFleetsResponse} returns this
 */
proto.fleetcoordination.ListFleetsResponse.prototype.clearError = function() {
  return this.setError(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.fleetcoordination.ListFleetsResponse.prototype.hasError = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fleetcoordination.ListFleetManagersRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.fleetcoordination.ListFleetManagersRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fleetcoordination.ListFleetManagersRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fleetcoordination.ListFleetManagersRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fleetcoordination.ListFleetManagersRequest}
 */
proto.fleetcoordination.ListFleetManagersRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fleetcoordination.ListFleetManagersRequest;
  return proto.fleetcoordination.ListFleetManagersRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fleetcoordination.ListFleetManagersRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fleetcoordination.ListFleetManagersRequest}
 */
proto.fleetcoordination.ListFleetManagersRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fleetcoordination.ListFleetManagersRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fleetcoordination.ListFleetManagersRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fleetcoordination.ListFleetManagersRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fleetcoordination.ListFleetManagersRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.fleetcoordination.ListFleetManagersResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fleetcoordination.ListFleetManagersResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.fleetcoordination.ListFleetManagersResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fleetcoordination.ListFleetManagersResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fleetcoordination.ListFleetManagersResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    managersList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    error: (f = msg.getError()) && proto.fleetcoordination.ErrorDetail.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fleetcoordination.ListFleetManagersResponse}
 */
proto.fleetcoordination.ListFleetManagersResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fleetcoordination.ListFleetManagersResponse;
  return proto.fleetcoordination.ListFleetManagersResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fleetcoordination.ListFleetManagersResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fleetcoordination.ListFleetManagersResponse}
 */
proto.fleetcoordination.ListFleetManagersResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addManagers(value);
      break;
    case 2:
      var value = new proto.fleetcoordination.ErrorDetail;
      reader.readMessage(value,proto.fleetcoordination.ErrorDetail.deserializeBinaryFromReader);
      msg.setError(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fleetcoordination.ListFleetManagersResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fleetcoordination.ListFleetManagersResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fleetcoordination.ListFleetManagersResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fleetcoordination.ListFleetManagersResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getManagersList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = message.getError();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.fleetcoordination.ErrorDetail.serializeBinaryToWriter
    );
  }
};


/**
 * repeated string managers = 1;
 * @return {!Array<string>}
 */
proto.fleetcoordination.ListFleetManagersResponse.prototype.getManagersList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.fleetcoordination.ListFleetManagersResponse} returns this
 */
proto.fleetcoordination.ListFleetManagersResponse.prototype.setManagersList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.fleetcoordination.ListFleetManagersResponse} returns this
 */
proto.fleetcoordination.ListFleetManagersResponse.prototype.addManagers = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.fleetcoordination.ListFleetManagersResponse} returns this
 */
proto.fleetcoordination.ListFleetManagersResponse.prototype.clearManagersList = function() {
  return this.setManagersList([]);
};


/**
 * optional ErrorDetail error = 2;
 * @return {?proto.fleetcoordination.ErrorDetail}
 */
proto.fleetcoordination.ListFleetManagersResponse.prototype.getError = function() {
  return /** @type{?proto.fleetcoordination.ErrorDetail} */ (
    jspb.Message.getWrapperField(this, proto.fleetcoordination.ErrorDetail, 2));
};


/**
 * @param {?proto.fleetcoordination.ErrorDetail|undefined} value
 * @return {!proto.fleetcoordination.ListFleetManagersResponse} returns this
*/
proto.fleetcoordination.ListFleetManagersResponse.prototype.setError = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.fleetcoordination.ListFleetManagersResponse} returns this
 */
proto.fleetcoordination.ListFleetManagersResponse.prototype.clearError = function() {
  return this.setError(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.fleetcoordination.ListFleetManagersResponse.prototype.hasError = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fleetcoordination.DeleteFleetRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.fleetcoordination.DeleteFleetRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fleetcoordination.DeleteFleetRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fleetcoordination.DeleteFleetRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    fleet: (f = msg.getFleet()) && proto.fleetcoordination.Fleet.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fleetcoordination.DeleteFleetRequest}
 */
proto.fleetcoordination.DeleteFleetRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fleetcoordination.DeleteFleetRequest;
  return proto.fleetcoordination.DeleteFleetRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fleetcoordination.DeleteFleetRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fleetcoordination.DeleteFleetRequest}
 */
proto.fleetcoordination.DeleteFleetRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.fleetcoordination.Fleet;
      reader.readMessage(value,proto.fleetcoordination.Fleet.deserializeBinaryFromReader);
      msg.setFleet(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fleetcoordination.DeleteFleetRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fleetcoordination.DeleteFleetRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fleetcoordination.DeleteFleetRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fleetcoordination.DeleteFleetRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFleet();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.fleetcoordination.Fleet.serializeBinaryToWriter
    );
  }
};


/**
 * optional Fleet fleet = 1;
 * @return {?proto.fleetcoordination.Fleet}
 */
proto.fleetcoordination.DeleteFleetRequest.prototype.getFleet = function() {
  return /** @type{?proto.fleetcoordination.Fleet} */ (
    jspb.Message.getWrapperField(this, proto.fleetcoordination.Fleet, 1));
};


/**
 * @param {?proto.fleetcoordination.Fleet|undefined} value
 * @return {!proto.fleetcoordination.DeleteFleetRequest} returns this
*/
proto.fleetcoordination.DeleteFleetRequest.prototype.setFleet = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.fleetcoordination.DeleteFleetRequest} returns this
 */
proto.fleetcoordination.DeleteFleetRequest.prototype.clearFleet = function() {
  return this.setFleet(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.fleetcoordination.DeleteFleetRequest.prototype.hasFleet = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fleetcoordination.DeleteFleetResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.fleetcoordination.DeleteFleetResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fleetcoordination.DeleteFleetResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fleetcoordination.DeleteFleetResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    result: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    error: (f = msg.getError()) && proto.fleetcoordination.ErrorDetail.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fleetcoordination.DeleteFleetResponse}
 */
proto.fleetcoordination.DeleteFleetResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fleetcoordination.DeleteFleetResponse;
  return proto.fleetcoordination.DeleteFleetResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fleetcoordination.DeleteFleetResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fleetcoordination.DeleteFleetResponse}
 */
proto.fleetcoordination.DeleteFleetResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setResult(value);
      break;
    case 2:
      var value = new proto.fleetcoordination.ErrorDetail;
      reader.readMessage(value,proto.fleetcoordination.ErrorDetail.deserializeBinaryFromReader);
      msg.setError(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fleetcoordination.DeleteFleetResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fleetcoordination.DeleteFleetResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fleetcoordination.DeleteFleetResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fleetcoordination.DeleteFleetResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResult();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getError();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.fleetcoordination.ErrorDetail.serializeBinaryToWriter
    );
  }
};


/**
 * optional bool result = 1;
 * @return {boolean}
 */
proto.fleetcoordination.DeleteFleetResponse.prototype.getResult = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.fleetcoordination.DeleteFleetResponse} returns this
 */
proto.fleetcoordination.DeleteFleetResponse.prototype.setResult = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional ErrorDetail error = 2;
 * @return {?proto.fleetcoordination.ErrorDetail}
 */
proto.fleetcoordination.DeleteFleetResponse.prototype.getError = function() {
  return /** @type{?proto.fleetcoordination.ErrorDetail} */ (
    jspb.Message.getWrapperField(this, proto.fleetcoordination.ErrorDetail, 2));
};


/**
 * @param {?proto.fleetcoordination.ErrorDetail|undefined} value
 * @return {!proto.fleetcoordination.DeleteFleetResponse} returns this
*/
proto.fleetcoordination.DeleteFleetResponse.prototype.setError = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.fleetcoordination.DeleteFleetResponse} returns this
 */
proto.fleetcoordination.DeleteFleetResponse.prototype.clearError = function() {
  return this.setError(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.fleetcoordination.DeleteFleetResponse.prototype.hasError = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fleetcoordination.Fleet.prototype.toObject = function(opt_includeInstance) {
  return proto.fleetcoordination.Fleet.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fleetcoordination.Fleet} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fleetcoordination.Fleet.toObject = function(includeInstance, msg) {
  var f, obj = {
    fleetid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    location: jspb.Message.getFieldWithDefault(msg, 2, ""),
    fleetmanager: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fleetcoordination.Fleet}
 */
proto.fleetcoordination.Fleet.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fleetcoordination.Fleet;
  return proto.fleetcoordination.Fleet.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fleetcoordination.Fleet} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fleetcoordination.Fleet}
 */
proto.fleetcoordination.Fleet.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFleetid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setLocation(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setFleetmanager(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fleetcoordination.Fleet.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fleetcoordination.Fleet.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fleetcoordination.Fleet} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fleetcoordination.Fleet.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFleetid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLocation();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getFleetmanager();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string fleetId = 1;
 * @return {string}
 */
proto.fleetcoordination.Fleet.prototype.getFleetid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.fleetcoordination.Fleet} returns this
 */
proto.fleetcoordination.Fleet.prototype.setFleetid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string location = 2;
 * @return {string}
 */
proto.fleetcoordination.Fleet.prototype.getLocation = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.fleetcoordination.Fleet} returns this
 */
proto.fleetcoordination.Fleet.prototype.setLocation = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string fleetManager = 3;
 * @return {string}
 */
proto.fleetcoordination.Fleet.prototype.getFleetmanager = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.fleetcoordination.Fleet} returns this
 */
proto.fleetcoordination.Fleet.prototype.setFleetmanager = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fleetcoordination.ErrorDetail.prototype.toObject = function(opt_includeInstance) {
  return proto.fleetcoordination.ErrorDetail.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fleetcoordination.ErrorDetail} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fleetcoordination.ErrorDetail.toObject = function(includeInstance, msg) {
  var f, obj = {
    message: jspb.Message.getFieldWithDefault(msg, 1, ""),
    details: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fleetcoordination.ErrorDetail}
 */
proto.fleetcoordination.ErrorDetail.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fleetcoordination.ErrorDetail;
  return proto.fleetcoordination.ErrorDetail.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fleetcoordination.ErrorDetail} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fleetcoordination.ErrorDetail}
 */
proto.fleetcoordination.ErrorDetail.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDetails(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fleetcoordination.ErrorDetail.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fleetcoordination.ErrorDetail.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fleetcoordination.ErrorDetail} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fleetcoordination.ErrorDetail.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDetails();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string message = 1;
 * @return {string}
 */
proto.fleetcoordination.ErrorDetail.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.fleetcoordination.ErrorDetail} returns this
 */
proto.fleetcoordination.ErrorDetail.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string details = 2;
 * @return {string}
 */
proto.fleetcoordination.ErrorDetail.prototype.getDetails = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.fleetcoordination.ErrorDetail} returns this
 */
proto.fleetcoordination.ErrorDetail.prototype.setDetails = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


goog.object.extend(exports, proto.fleetcoordination);
