/**
 * @fileoverview gRPC-Web generated client stub for fleetcoordination
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.27.2
// source: api_specification_am_fleet_coordination.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as api_specification_am_fleet_coordination_pb from './api_specification_am_fleet_coordination_pb'; // proto import: "api_specification_am_fleet_coordination.proto"


export class FleetCoordinatorServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateNewFleet = new grpcWeb.MethodDescriptor(
    '/fleetcoordination.FleetCoordinatorService/CreateNewFleet',
    grpcWeb.MethodType.UNARY,
    api_specification_am_fleet_coordination_pb.CreateNewFleetRequest,
    api_specification_am_fleet_coordination_pb.CreateNewFleetResponse,
    (request: api_specification_am_fleet_coordination_pb.CreateNewFleetRequest) => {
      return request.serializeBinary();
    },
    api_specification_am_fleet_coordination_pb.CreateNewFleetResponse.deserializeBinary
  );

  createNewFleet(
    request: api_specification_am_fleet_coordination_pb.CreateNewFleetRequest,
    metadata?: grpcWeb.Metadata | null): Promise<api_specification_am_fleet_coordination_pb.CreateNewFleetResponse>;

  createNewFleet(
    request: api_specification_am_fleet_coordination_pb.CreateNewFleetRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: api_specification_am_fleet_coordination_pb.CreateNewFleetResponse) => void): grpcWeb.ClientReadableStream<api_specification_am_fleet_coordination_pb.CreateNewFleetResponse>;

  createNewFleet(
    request: api_specification_am_fleet_coordination_pb.CreateNewFleetRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: api_specification_am_fleet_coordination_pb.CreateNewFleetResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/fleetcoordination.FleetCoordinatorService/CreateNewFleet',
        request,
        metadata || {},
        this.methodDescriptorCreateNewFleet,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/fleetcoordination.FleetCoordinatorService/CreateNewFleet',
    request,
    metadata || {},
    this.methodDescriptorCreateNewFleet);
  }

  methodDescriptorChangeFleetManager = new grpcWeb.MethodDescriptor(
    '/fleetcoordination.FleetCoordinatorService/ChangeFleetManager',
    grpcWeb.MethodType.UNARY,
    api_specification_am_fleet_coordination_pb.ChangeFleetManagerRequest,
    api_specification_am_fleet_coordination_pb.ChangeFleetManagerResponse,
    (request: api_specification_am_fleet_coordination_pb.ChangeFleetManagerRequest) => {
      return request.serializeBinary();
    },
    api_specification_am_fleet_coordination_pb.ChangeFleetManagerResponse.deserializeBinary
  );

  changeFleetManager(
    request: api_specification_am_fleet_coordination_pb.ChangeFleetManagerRequest,
    metadata?: grpcWeb.Metadata | null): Promise<api_specification_am_fleet_coordination_pb.ChangeFleetManagerResponse>;

  changeFleetManager(
    request: api_specification_am_fleet_coordination_pb.ChangeFleetManagerRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: api_specification_am_fleet_coordination_pb.ChangeFleetManagerResponse) => void): grpcWeb.ClientReadableStream<api_specification_am_fleet_coordination_pb.ChangeFleetManagerResponse>;

  changeFleetManager(
    request: api_specification_am_fleet_coordination_pb.ChangeFleetManagerRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: api_specification_am_fleet_coordination_pb.ChangeFleetManagerResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/fleetcoordination.FleetCoordinatorService/ChangeFleetManager',
        request,
        metadata || {},
        this.methodDescriptorChangeFleetManager,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/fleetcoordination.FleetCoordinatorService/ChangeFleetManager',
    request,
    metadata || {},
    this.methodDescriptorChangeFleetManager);
  }

  methodDescriptorListFleets = new grpcWeb.MethodDescriptor(
    '/fleetcoordination.FleetCoordinatorService/ListFleets',
    grpcWeb.MethodType.UNARY,
    api_specification_am_fleet_coordination_pb.ListFleetsRequest,
    api_specification_am_fleet_coordination_pb.ListFleetsResponse,
    (request: api_specification_am_fleet_coordination_pb.ListFleetsRequest) => {
      return request.serializeBinary();
    },
    api_specification_am_fleet_coordination_pb.ListFleetsResponse.deserializeBinary
  );

  listFleets(
    request: api_specification_am_fleet_coordination_pb.ListFleetsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<api_specification_am_fleet_coordination_pb.ListFleetsResponse>;

  listFleets(
    request: api_specification_am_fleet_coordination_pb.ListFleetsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: api_specification_am_fleet_coordination_pb.ListFleetsResponse) => void): grpcWeb.ClientReadableStream<api_specification_am_fleet_coordination_pb.ListFleetsResponse>;

  listFleets(
    request: api_specification_am_fleet_coordination_pb.ListFleetsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: api_specification_am_fleet_coordination_pb.ListFleetsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/fleetcoordination.FleetCoordinatorService/ListFleets',
        request,
        metadata || {},
        this.methodDescriptorListFleets,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/fleetcoordination.FleetCoordinatorService/ListFleets',
    request,
    metadata || {},
    this.methodDescriptorListFleets);
  }

  methodDescriptorListFleetManagers = new grpcWeb.MethodDescriptor(
    '/fleetcoordination.FleetCoordinatorService/ListFleetManagers',
    grpcWeb.MethodType.UNARY,
    api_specification_am_fleet_coordination_pb.ListFleetManagersRequest,
    api_specification_am_fleet_coordination_pb.ListFleetManagersResponse,
    (request: api_specification_am_fleet_coordination_pb.ListFleetManagersRequest) => {
      return request.serializeBinary();
    },
    api_specification_am_fleet_coordination_pb.ListFleetManagersResponse.deserializeBinary
  );

  listFleetManagers(
    request: api_specification_am_fleet_coordination_pb.ListFleetManagersRequest,
    metadata?: grpcWeb.Metadata | null): Promise<api_specification_am_fleet_coordination_pb.ListFleetManagersResponse>;

  listFleetManagers(
    request: api_specification_am_fleet_coordination_pb.ListFleetManagersRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: api_specification_am_fleet_coordination_pb.ListFleetManagersResponse) => void): grpcWeb.ClientReadableStream<api_specification_am_fleet_coordination_pb.ListFleetManagersResponse>;

  listFleetManagers(
    request: api_specification_am_fleet_coordination_pb.ListFleetManagersRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: api_specification_am_fleet_coordination_pb.ListFleetManagersResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/fleetcoordination.FleetCoordinatorService/ListFleetManagers',
        request,
        metadata || {},
        this.methodDescriptorListFleetManagers,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/fleetcoordination.FleetCoordinatorService/ListFleetManagers',
    request,
    metadata || {},
    this.methodDescriptorListFleetManagers);
  }

  methodDescriptorDeleteFleet = new grpcWeb.MethodDescriptor(
    '/fleetcoordination.FleetCoordinatorService/DeleteFleet',
    grpcWeb.MethodType.UNARY,
    api_specification_am_fleet_coordination_pb.DeleteFleetRequest,
    api_specification_am_fleet_coordination_pb.DeleteFleetResponse,
    (request: api_specification_am_fleet_coordination_pb.DeleteFleetRequest) => {
      return request.serializeBinary();
    },
    api_specification_am_fleet_coordination_pb.DeleteFleetResponse.deserializeBinary
  );

  deleteFleet(
    request: api_specification_am_fleet_coordination_pb.DeleteFleetRequest,
    metadata?: grpcWeb.Metadata | null): Promise<api_specification_am_fleet_coordination_pb.DeleteFleetResponse>;

  deleteFleet(
    request: api_specification_am_fleet_coordination_pb.DeleteFleetRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: api_specification_am_fleet_coordination_pb.DeleteFleetResponse) => void): grpcWeb.ClientReadableStream<api_specification_am_fleet_coordination_pb.DeleteFleetResponse>;

  deleteFleet(
    request: api_specification_am_fleet_coordination_pb.DeleteFleetRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: api_specification_am_fleet_coordination_pb.DeleteFleetResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/fleetcoordination.FleetCoordinatorService/DeleteFleet',
        request,
        metadata || {},
        this.methodDescriptorDeleteFleet,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/fleetcoordination.FleetCoordinatorService/DeleteFleet',
    request,
    metadata || {},
    this.methodDescriptorDeleteFleet);
  }

}

